[gfroerli_api]
api_url = "http://localhost:3000/api"
api_key = "gfroerli-example-api-key"

[logging]
level = "info,lindas_hydrodata_fetcher=debug"

# Linth, Weesen
[[stations]]
foen_station_id = 2104
gfroerli_sensor_id = 1

# Sihl, ZÃ¼rich
[[stations]]
foen_station_id = 2176
gfroerli_sensor_id = 2

# Aare, Bern
[[stations]]
foen_station_id = 2135
gfroerli_sensor_id = 3
